window.JASTELO_PROPERTIES = {
  turu: {
    index: "01",
    code: "JA-001 · ALTO DO TURU",
    title: "Residência Térrea Alto do Turu",
    status: "Pronta para morar",
    area: "117,62 m²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "2024",
    price: "R$ 530.000",
    location: "Alto do Turu, São José de Ribamar — MA",
    mapQuery: "R. 19, 10, Novo Cohatrac, São José de Ribamar, MA",
    description: "Projetada com traços retos e volumes marcantes, esta residência combina integração, funcionalidade e sofisticação. Os ambientes foram planejados para oferecer conforto no dia a dia, iluminação natural e uma relação agradável entre o interior e a área de lazer.",
    highlights: ["Piscina privativa", "Área gourmet com churrasqueira", "Jardim de inverno", "Sala de estar integrada", "Arquitetura contemporânea", "Acabamento de alto padrão"],
    images: ["assets/jastelo-40.png", "assets/jastelo-38.png", "assets/jastelo-36.png"]
  },
  "turu-sem-piscina": {
    index: "02",
    code: "JA-002 · ALTO DO TURU",
    title: "Residência Térrea Alto do Turu",
    status: "Pronta para morar · sem piscina",
    area: "117,62 m²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "2024",
    price: "R$ 500.000",
    location: "Alto do Turu, São José de Ribamar — MA",
    mapQuery: "R. 19, 10, Novo Cohatrac, São José de Ribamar, MA",
    description: "Uma casa térrea contemporânea para quem valoriza espaços integrados, praticidade e elegância. A planta aproveita cada metro quadrado com circulação fluida, ambientes bem iluminados e acabamento cuidadosamente selecionado.",
    highlights: ["Jardim de inverno", "Área gourmet com churrasqueira", "Sala de estar integrada", "Cozinha funcional", "Arquitetura contemporânea", "Garagem para 2 veículos"],
    images: ["assets/jastelo-28.png", "assets/jastelo-38.png", "assets/jastelo-12.png"]
  },
  aracagy: {
    index: "03",
    code: "JA-003 · ARAÇAGY",
    title: "Residência Térrea Araçagy",
    status: "Lançamento",
    area: "156,67 m²",
    rooms: "4 suítes",
    bathrooms: "5 banheiros",
    garage: "2 vagas",
    year: "Em construção",
    price: "R$ 999.000",
    location: "Araçagy, São José de Ribamar — MA",
    mapQuery: "Araçagy, São José de Ribamar, MA",
    description: "Com estilo contemporâneo marcado por linhas retas, volumes imponentes e integração total dos ambientes, esta residência reúne sofisticação, funcionalidade e alto padrão construtivo em uma localização valorizada.",
    highlights: ["4 suítes", "Piscina privativa", "Varanda coberta", "Área gourmet", "Pé-direito alto", "Ambientes integrados"],
    images: ["assets/aracagy-lancamento-capa.jpg", "assets/aracagy-lazer.jpg", "assets/aracagy-planta.jpg"]
  },
  "planta-sem-piscina": {
    index: "04",
    code: "JA-004 · ALTO DO TURU",
    title: "Residência Alto do Turu na planta",
    status: "Venda na planta · sem piscina",
    area: "117,62 m²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "Projeto em lançamento",
    price: "R$ 500.000",
    location: "Alto do Turu, São José de Ribamar — MA",
    mapQuery: "Alto do Turu, São José de Ribamar, MA",
    description: "Um projeto térreo contemporâneo para comprar ainda na planta, com distribuição inteligente e o padrão de acabamento Jastelo. Uma oportunidade para acompanhar a evolução da obra e preparar o novo lar com antecedência.",
    highlights: ["Compra na planta", "3 quartos", "Jardim de inverno", "Área gourmet", "Sala integrada", "2 vagas de garagem"],
    images: ["assets/alto-turu-planta-sem-piscina.jpg", "assets/jastelo-28.png", "assets/jastelo-38.png"]
  },
  "planta-com-piscina": {
    index: "05",
    code: "JA-005 · ALTO DO TURU",
    title: "Residência Alto do Turu na planta",
    status: "Venda na planta · com piscina",
    area: "117,62 m²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "Projeto em lançamento",
    price: "R$ 530.000",
    location: "Alto do Turu, São José de Ribamar — MA",
    mapQuery: "Alto do Turu, São José de Ribamar, MA",
    description: "A versão com piscina combina o projeto térreo funcional da Jastelo com uma área externa preparada para receber, descansar e viver bons momentos. Disponível para aquisição ainda na planta.",
    highlights: ["Compra na planta", "Piscina privativa", "3 quartos", "Jardim de inverno", "Área gourmet", "2 vagas de garagem"],
    images: ["assets/alto-turu-planta-com-piscina.jpg", "assets/jastelo-40.png", "assets/jastelo-36.png"]
  },
  duplex: {
    index: "06",
    code: "PORTFÓLIO · ARAÇAGY PRAIA AZUL",
    title: "Duplex Araçagy Praia Azul",
    status: "Todas as unidades vendidas",
    area: "Casa duplex",
    rooms: "4 suítes",
    bathrooms: "Alto padrão",
    garage: "Garagem ampla",
    year: "Concluído",
    price: "R$ 899.000",
    location: "Araçagy Praia Azul — MA",
    mapQuery: "Praia do Araçagy, São José de Ribamar, MA",
    description: "Com fachada imponente, linhas retas e volumetria marcante, este empreendimento residencial expressa o equilíbrio entre funcionalidade e alto padrão que orienta os projetos da Jastelo. Todas as unidades foram comercializadas.",
    highlights: ["Empreendimento concluído", "4 suítes", "Casa duplex", "Garagem ampla", "Fachada contemporânea", "Todas as unidades vendidas"],
    images: ["assets/jastelo-03.png", "assets/jastelo-15.png", "assets/jastelo-18.jpg", "assets/jastelo-25.jpg"]
  }
};
