window.JASTELO_PROPERTIES = {
  turu: {
    index: "01",
    code: "JA-001 Â· ALTO DO TURU",
    title: "ResidÃªncia TÃ©rrea Alto do Turu",
    status: "Pronta para morar",
    area: "117,62 mÂ²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "2024",
    price: "R$ 530.000",
    location: "Alto do Turu, SÃ£o JosÃ© de Ribamar â€” MA",
    mapQuery: "R. 19, 10, Novo Cohatrac, SÃ£o JosÃ© de Ribamar, MA",
    description: "Projetada com traÃ§os retos e volumes marcantes, esta residÃªncia combina integraÃ§Ã£o, funcionalidade e sofisticaÃ§Ã£o. Os ambientes foram planejados para oferecer conforto no dia a dia, iluminaÃ§Ã£o natural e uma relaÃ§Ã£o agradÃ¡vel entre o interior e a Ã¡rea de lazer.",
    highlights: ["Piscina privativa", "Ãrea gourmet com churrasqueira", "Jardim de inverno", "Sala de estar integrada", "Arquitetura contemporÃ¢nea", "Acabamento de alto padrÃ£o"],
    images: ["assets/jastelo-40.png", "assets/jastelo-38.png", "assets/jastelo-36.png"]
  },
  "turu-sem-piscina": {
    index: "02",
    code: "JA-002 Â· ALTO DO TURU",
    title: "ResidÃªncia TÃ©rrea Alto do Turu",
    status: "Pronta para morar Â· sem piscina",
    area: "117,62 mÂ²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "2024",
    price: "R$ 500.000",
    location: "Alto do Turu, SÃ£o JosÃ© de Ribamar â€” MA",
    mapQuery: "R. 19, 10, Novo Cohatrac, SÃ£o JosÃ© de Ribamar, MA",
    description: "Uma casa tÃ©rrea contemporÃ¢nea para quem valoriza espaÃ§os integrados, praticidade e elegÃ¢ncia. A planta aproveita cada metro quadrado com circulaÃ§Ã£o fluida, ambientes bem iluminados e acabamento cuidadosamente selecionado.",
    highlights: ["Jardim de inverno", "Ãrea gourmet com churrasqueira", "Sala de estar integrada", "Cozinha funcional", "Arquitetura contemporÃ¢nea", "Garagem para 2 veÃ­culos"],
    images: ["assets/jastelo-28.png", "assets/jastelo-38.png", "assets/jastelo-12.png"]
  },
  aracagy: {
    index: "03",
    code: "JA-003 Â· ARAÃ‡AGY",
    title: "ResidÃªncia TÃ©rrea AraÃ§agy",
    status: "LanÃ§amento",
    area: "156,67 mÂ²",
    rooms: "4 suÃ­tes",
    bathrooms: "5 banheiros",
    garage: "2 vagas",
    year: "Em construÃ§Ã£o",
    price: "R$ 999.000",
    location: "AraÃ§agy, SÃ£o JosÃ© de Ribamar â€” MA",
    mapQuery: "AraÃ§agy, SÃ£o JosÃ© de Ribamar, MA",
    description: "Com estilo contemporÃ¢neo marcado por linhas retas, volumes imponentes e integraÃ§Ã£o total dos ambientes, esta residÃªncia reÃºne sofisticaÃ§Ã£o, funcionalidade e alto padrÃ£o construtivo em uma localizaÃ§Ã£o valorizada.",
    highlights: ["4 suÃ­tes", "Piscina privativa", "Varanda coberta", "Ãrea gourmet", "PÃ©-direito alto", "Ambientes integrados"],
    images: ["assets/aracagy-lancamento-capa.jpg", "assets/aracagy-lazer.jpg", "assets/aracagy-planta.jpg"]
  },
  "planta-sem-piscina": {
    index: "04",
    code: "JA-004 Â· ALTO DO TURU",
    title: "ResidÃªncia Alto do Turu na planta",
    status: "Venda na planta Â· sem piscina",
    area: "117,62 mÂ²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "Projeto em lanÃ§amento",
    price: "R$ 500.000",
    location: "Alto do Turu, SÃ£o JosÃ© de Ribamar â€” MA",
    mapQuery: "Alto do Turu, SÃ£o JosÃ© de Ribamar, MA",
    description: "Um projeto tÃ©rreo contemporÃ¢neo para comprar ainda na planta, com distribuiÃ§Ã£o inteligente e o padrÃ£o de acabamento Jastelo. Uma oportunidade para acompanhar a evoluÃ§Ã£o da obra e preparar o novo lar com antecedÃªncia.",
    highlights: ["Compra na planta", "3 quartos", "Jardim de inverno", "Ãrea gourmet", "Sala integrada", "2 vagas de garagem"],
    images: ["assets/alto-turu-planta-sem-piscina.jpg", "assets/jastelo-28.png", "assets/jastelo-38.png"]
  },
  "planta-com-piscina": {
    index: "05",
    code: "JA-005 Â· ALTO DO TURU",
    title: "ResidÃªncia Alto do Turu na planta",
    status: "Venda na planta Â· com piscina",
    area: "117,62 mÂ²",
    rooms: "3 quartos",
    bathrooms: "3 banheiros",
    garage: "2 vagas",
    year: "Projeto em lanÃ§amento",
    price: "R$ 530.000",
    location: "Alto do Turu, SÃ£o JosÃ© de Ribamar â€” MA",
    mapQuery: "Alto do Turu, SÃ£o JosÃ© de Ribamar, MA",
    description: "A versÃ£o com piscina combina o projeto tÃ©rreo funcional da Jastelo com uma Ã¡rea externa preparada para receber, descansar e viver bons momentos. DisponÃ­vel para aquisiÃ§Ã£o ainda na planta.",
    highlights: ["Compra na planta", "Piscina privativa", "3 quartos", "Jardim de inverno", "Ãrea gourmet", "2 vagas de garagem"],
    images: ["assets/alto-turu-planta-com-piscina.jpg", "assets/jastelo-40.png", "assets/jastelo-36.png"]
  },
  duplex: {
    index: "06",
    code: "PORTFÃ“LIO Â· ARAÃ‡AGY PRAIA AZUL",
    title: "Duplex AraÃ§agy Praia Azul",
    status: "Todas as unidades vendidas",
    area: "Casa duplex",
    rooms: "4 suÃ­tes",
    bathrooms: "Alto padrÃ£o",
    garage: "Garagem ampla",
    year: "ConcluÃ­do",
    price: "R$ 899.000",
    location: "AraÃ§agy Praia Azul â€” MA",
    mapQuery: "Praia do AraÃ§agy, SÃ£o JosÃ© de Ribamar, MA",
    description: "Com fachada imponente, linhas retas e volumetria marcante, este empreendimento residencial expressa o equilÃ­brio entre funcionalidade e alto padrÃ£o que orienta os projetos da Jastelo. Todas as unidades foram comercializadas.",
    highlights: ["Empreendimento concluÃ­do", "4 suÃ­tes", "Casa duplex", "Garagem ampla", "Fachada contemporÃ¢nea", "Todas as unidades vendidas"],
    images: ["assets/jastelo-03.png", "assets/jastelo-15.png", "assets/jastelo-18.jpg", "assets/jastelo-25.jpg"]
  }
};
