const navigation=document.querySelector('.main-nav');if(navigation&&!navigation.querySelector('[href="trabalhe-conosco.html"]')){const careersLink=document.createElement('a');careersLink.href='trabalhe-conosco.html';careersLink.textContent='Trabalhe conosco';navigation.appendChild(careersLink)}
const menuButton=document.querySelector('.menu-button');
if(menuButton){menuButton.addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');menuButton.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',()=>{document.body.classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}))}

const cards=[...document.querySelectorAll('.property-card')],filterButtons=[...document.querySelectorAll('[data-filter]')],search=document.querySelector('#property-search'),noResults=document.querySelector('.no-results');let activeFilter='todos';
function filterCards(){if(!cards.length)return;const term=search?.value.trim().toLocaleLowerCase('pt-BR')||'';let visible=0;cards.forEach(card=>{const matches=(activeFilter==='todos'||card.dataset.status===activeFilter)&&(!term||card.dataset.search.includes(term));card.hidden=!matches;if(matches)visible++});if(noResults)noResults.hidden=visible!==0}
filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(item=>item.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;filterCards()}));search?.addEventListener('input',filterCards);

const properties={turu:{code:'JA-001 \u00b7 ALTO DO TURU',title:'Resid\u00eancia T\u00e9rrea com piscina',area:'117,62 m\u00b2',rooms:'3',price:'R$ 530.000',image:'assets/jastelo-40.png'},'turu-sem-piscina':{code:'JA-002 \u00b7 ALTO DO TURU',title:'Resid\u00eancia T\u00e9rrea sem piscina',area:'117,62 m\u00b2',rooms:'3',price:'R$ 500.000',image:'assets/jastelo-28.png'},aracagy:{code:'JA-003 \u00b7 ARA\u00c7AGY',title:'Residencial T\u00e9rrea Ara\u00e7agy',area:'156,67 m\u00b2',rooms:'4 su\u00edtes',price:'R$ 999.000',image:'assets/aracagy-lancamento-capa.jpg'},'planta-sem-piscina':{code:'JA-004 \u00b7 ALTO DO TURU \u00b7 NA PLANTA',title:'Alto do Turu na planta \u00b7 sem piscina',area:'117,62 m\u00b2',rooms:'3 quartos',price:'R$ 500.000',image:'assets/alto-turu-planta-sem-piscina.jpg'},'planta-com-piscina':{code:'JA-005 \u00b7 ALTO DO TURU \u00b7 NA PLANTA',title:'Alto do Turu na planta \u00b7 com piscina',area:'117,62 m\u00b2',rooms:'3 quartos',price:'R$ 530.000',image:'assets/alto-turu-planta-com-piscina.jpg'},duplex:{code:'PORTF\u00d3LIO \u00b7 ARA\u00c7AGY PRAIA AZUL',title:'Duplex Ara\u00e7agy Praia Azul \u2014 vendido',area:'Casa duplex',rooms:'4 su\u00edtes',price:'R$ 899.000',image:'assets/jastelo-03.png'}};
const dialog=document.querySelector('#property-dialog'),mainImage=document.querySelector('#dialog-main-image');
if(dialog&&mainImage){document.querySelectorAll('.property-open').forEach(button=>button.addEventListener('click',()=>{const property=properties[button.dataset.property];if(!property)return;document.querySelector('#dialog-code').textContent=property.code;document.querySelector('#dialog-title').textContent=property.title;document.querySelector('#dialog-area').textContent=property.area;document.querySelector('#dialog-rooms').textContent=property.rooms;document.querySelector('#dialog-price').textContent=property.price;mainImage.src=property.image;const message=`Ol\u00e1, Thayn\u00e1! Gostaria de agendar uma visita para conhecer: ${property.title}.`;document.querySelector('#dialog-whatsapp').href=`https://wa.me/5519991570231?text=${encodeURIComponent(message)}`;dialog.showModal()}));document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});document.querySelectorAll('.thumbs button').forEach(button=>button.addEventListener('click',()=>{mainImage.src=button.dataset.image}))}

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
const leadForm=document.querySelector('#lead-form');leadForm?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(leadForm),message=`Ol\u00e1, Thayn\u00e1! Sou ${data.get('nome')}. Tenho interesse em: ${data.get('interesse')}. Meu telefone \u00e9 ${data.get('telefone')}.`;document.querySelector('.form-feedback').textContent='Tudo certo! Abrindo o WhatsApp para concluir seu atendimento\u2026';window.open(`https://wa.me/5519991570231?text=${encodeURIComponent(message)}`,'_blank','noopener')});
