const navigation=document.querySelector('.main-nav');if(navigation&&!navigation.querySelector('[href="trabalhe-conosco.html"]')){const careersLink=document.createElement('a');careersLink.href='trabalhe-conosco.html';careersLink.textContent='Trabalhe conosco';navigation.appendChild(careersLink)}
const menuButton=document.querySelector('.menu-button');
if(menuButton){menuButton.addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');menuButton.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',()=>{document.body.classList.remove('menu-open');menuButton.setAttribute('aria-expanded','false')}))}

const cards=[...document.querySelectorAll('.property-card')],filterButtons=[...document.querySelectorAll('[data-filter]')],search=document.querySelector('#property-search'),noResults=document.querySelector('.no-results');let activeFilter='todos';
function filterCards(){if(!cards.length)return;const term=search?.value.trim().toLocaleLowerCase('pt-BR')||'';let visible=0;cards.forEach(card=>{const matches=(activeFilter==='todos'||card.dataset.status===activeFilter)&&(!term||card.dataset.search.includes(term));card.hidden=!matches;if(matches)visible++});if(noResults)noResults.hidden=visible!==0}
filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(item=>item.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;filterCards()}));search?.addEventListener('input',filterCards);

document.querySelectorAll('.property-open').forEach(button=>button.addEventListener('click',()=>{const property=button.dataset.property;if(property)window.location.href=`propriedade.html?id=${encodeURIComponent(property)}`}));

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
const leadForm=document.querySelector('#lead-form');leadForm?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(leadForm),message=`Ol\u00e1, Thayn\u00e1! Sou ${data.get('nome')}. Tenho interesse em: ${data.get('interesse')}. Meu telefone \u00e9 ${data.get('telefone')}.`;document.querySelector('.form-feedback').textContent='Tudo certo! Abrindo o WhatsApp para concluir seu atendimento\u2026';window.open(`https://wa.me/5519991570231?text=${encodeURIComponent(message)}`,'_blank','noopener')});
